name: build_distribution
description: CLI tool for uploading APK to Google Drive.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
executables:
  build_distribution:

environment:
  sdk: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  googleapis: ^11.1.0
  googleapis_auth: ^1.4.1
  http: ^0.13.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

